easymart:
  auth:
    jwt:
      public-key: ${JWT_PUBLIC_KEY:classpath:certs/public.pem}
      private-key: ${JWT_PRIVATE_KEY:classpath:certs/private.pem}
      lifetime: ${JWT_LIFETIME:10800}

logging:
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss.SSS,${TIMEZONE:America/Sao_Paulo}
  level:
    root: ${LOG_LEVEL:info}

server:
  error:
    include-message: always
    include-binding-errors: always
  port: 8080
  servlet:
    context-path: /api/em-catalog
  tomcat:
    uri-encoding: UTF-8

spring:
  application:
    name: catalog
    timezone: ${TIMEZONE:America/Sao_Paulo}
  datasource:
    url: jdbc:postgresql://${DB_HOST:db}:5432/${DB_NAME:em_catalog}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:root}
  jmx:
    enabled: false
  jpa:
    open-in-view: true
    show-sql: false
    hibernate:
      ddl-auto: update
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
  output:
    ansi:
      enabled: ALWAYS
